### PR TITLE
VSCode Release v0.14.7

### PR DESCRIPTION
**Pull request by bugarela**

### CODE REVIEW

**Comment by lucab** [comment]
First of all, thanks for the release!
I was looking into picking up the new version from the marketplace, but the latest version I can see there is `0.14.6`: https://marketplace.visualstudio.com/items?itemName=informal.quint-vscode
Do you maybe still need to manually publish the latest release there?

**Comment by bugarela** [comment]
> First of all, thanks for the release! I was looking into picking up the new version from the marketplace, but the latest version I can see there is `0.14.6`: https://marketplace.visualstudio.com/items?itemName=informal.quint-vscode Do you maybe still need to manually publish the latest release there?

Yes! I was traveling and for some reason the command to push the release was not working on my laptop and I didn't find time to fix it. I'm now back home and will push this properly.

**Comment by bugarela** [comment]
Done: https://marketplace.visualstudio.com/items?itemName=informal.quint-vscode

**Comment by lucab** [comment]
Thanks!
I just noticed that this one is apparently lagging behind too: https://www.npmjs.com/package/@informalsystems/quint-language-server

**Comment by bugarela** [comment]
Right :facepalm:. Having this not automated is usually fine, but I guess it becomes a problem in non-ideal situations like this one :sweat_smile:. Just pushed it, should be updated in npm in a few mins.

Thanks a lot for keeping an eye on this - you avoided potentially loads of confusion in the future.

**Comment by lucab** [comment]
I'm having some hard time understanding what's going on, but apparently the `informal.quint-vscode-0.14.7` extension is somehow carrying an older version of `@informalsystems/quint` in its `node_modules` directory:
```
$ jq '.version' ${HOME}/.vscode/extensions/informal.quint-vscode-0.14.7/server/node_modules/@informalsystems/quint/package.json 

"0.22.1"
```

I initially thought there was something wrong in my local setup, but then I verified that this is actually coming from the `.vsix` bundle in the marketplace.
You can check it yourself by clicking on `Download Extension` in https://marketplace.visualstudio.com/items?itemName=informal.quint-vscode and then manually opening the zip archive.

**Comment by bugarela** [comment]
That's very weird! I believe there's a high chance that this is due to me preparing the release and then actually releasing from two different computers (I prepared it in my laptop, and pushed it (from the proper commit) from my home computer). Probably our script is not good enough to handle this scenario, and there are some missing commands that needed to be run (i.e. `npm install` from the release commit before pushing).

There's no way to change a release, but I'll cut a new version for VSCode tomorrow and open an issue to improve this setup. Again, thanks for checking and sorry for not testing this properly - it has been working fine until I did it a bit out of the ordinary way.

**Pull request merged**
