### PR TITLE
LSP configuration for Neovim

### PR DESCRIPTION
**Pull request by bugarela**
Hello :octocat: 

I've added some instructions on how to setup neovim with LSP. I'm not a neovim user, and my configuration is done through NixOS (home-manager), so I'm not 100% sure this instructions are the right way of doing things in a normal unix system. @konnov can you try them out, maybe?

- [-] Tests added for any new code
- [X] Documentation added for any new functionality
- [-] Entries added to the respective `CHANGELOG.md` for any new functionality
- [-] Feature table on [`README.md`](../README.md#roadmap) updated for any listed functionality

### CODE REVIEW

**Comment by konnov** [comment]
Hey @bugarela! I have followed the instructions, but it does not work for me. Perhaps, we need a section on troubleshooting. I have no idea, whether the server has started and how to check it in `nvim`.

**Comment by konnov** [comment]
Oh, it's actually working! `nvim` was not picking up the syntax file. I am updating the README file. Amazing!

Nevertheless, we should probably add a paragraph on how to see, what is not working.

**Comment by bugarela** [comment]
Ah, I see! The syntax instructions I just copied from comments inside `quint.vim`, I did not think they would differ for nvim (I'm using the tree-sitter highlighting in my config) - will update the comments as well.

**Comment by konnov** [comment]
I tried it in vim too, and it works. Amazing!

**Review by konnov — APPROVED** [review]
It's amazing. Works both with neovim and vim.

**Comment by bugarela** [comment]
@konnov I meant to add a troubleshooting section as you asked, but not having used vim/nvim before, I don't really know any troubleshooting better than "google stuff and look at the docs" :laughing:. Perhaps we can build this section over time, as people (and ourselves) find problems and solutions.

**Pull request merged**
