### PR TITLE
Add `--main` flag to `verify`

### LINKED ISSUE #925: Add `--main` to `verify`
Similar to the [command `run`](https://github.com/informalsystems/quint/blob/main/doc/quint.md#command-run), we should add the option `--main` to [verify](https://github.com/informalsystems/quint/blob/main/doc/quint.md#command-verify). Otherwise, it is impossible to verify a module that is named different from the filename, e.g., [prisoners](https://github.com/informalsystems/quint/blob/main/examples/puzzles/prisoners/prisoners.qnt).

### PR DESCRIPTION
**Pull request by thpani**
- [x] Tests added for any new code
- [x] Documentation added for any new functionality
- [ ] ~Entries added to the respective `CHANGELOG.md` for any new functionality~
- [ ] ~Feature table on [`README.md`](../README.md#roadmap) updated for any listed functionality~

Closes #925

### CODE REVIEW

**Review by bugarela — APPROVED** [review]
LGTM! I see there is a failing integration test. I think you might need to go back to using `export` to make sure the imported definitions from `prisoners` inside `prisoners3` are also available to modules importing `prisoners3`.

**Review by shonfeder — APPROVED** [review]

**Comment by konnov** [comment]
I think this will require a bit of refactoring once the fresh PRs by @bugarela are merged

**Comment by thpani** [comment]
Just to note: this is blocked on unifying import/export behavior #949

**Comment by thpani** [comment]
The prisoners example only works _either_ in the simulator _or_ with `verify` until https://github.com/informalsystems/quint/discussions/949 is resolved, so I've dropped it as an integration test for now. In any case, it's checked as part of the examples dashboard.

**Pull request merged**
