### PR TITLE
bump the grpc-js version and increase message sizes

### LINKED ISSUE #1458: `quint verify` fails with "Received message larger than max (7576431 vs. 4194304)"
I don't have a concrete spec at hand, but this happened multiple times to me. It's especially annoying when this message is output after hours of waiting:

```
Error: 8 RESOURCE_EXHAUSTED: Received message larger than max (7576431 vs. 4194304)
    at callErrorFromStatus (REDACTED/quint/quint/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (REDACTED/quint/quint/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at Object.onReceiveStatus (REDACTED/quint/quint/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (REDACTED/quint/quint/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at REDACTED/quint/quint/node_modules/@grpc/grpc-js/build/src/resolving-call.js:99:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (REDACTED/quint/quint/node_modules/@grpc/grpc-js/build/src/client.js:160:32)
    at ServiceClientImpl.run (REDACTED/quint/quint/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at Object.<anonymous> (REDACTED/quint/quint/dist/src/apalache.js:219:55)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Object.run (node:internal/util:346:12)
    at Object.check (REDACTED/quint/quint/dist/src/apalache.js:147:28)
    at REDACTED/quint/quint/dist/src/quintVerifier.js:32:53
    at EitherConstructor.asyncChain (REDACTED/quint/quint/node_modules/@sweet-monads/either/cjs/index.js:125:16)
    at verify (REDACTED/quint/quint/dist/src/quintVerifier.js:32:29) {
  code: 8,
  details: 'Received message larger than max (7576431 vs. 4194304)',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
```

After digging into `quintVerify.ts` and the Apalache server, I can conclude that there are two reasons:

 1. The JS frontend limits protobuf messages to 4MB, whereas the Scala backend was bumped to 8MB, see https://github.com/informalsystems/apalache/pull/2623.
 2. For some reason, the server returns a complete JSON representation of the module after `check`:
    https://github.com/informalsystems/apalache/blob/6d69a24e7dcaa5b688959dcc4c50d0fb49fbdfd7/shai/src/main/scala/at/forsyte/apalache/shai/v1/CmdExecutorService.scala#L99

I actually don't know about the reason for dumping the JSON IR back from `check`. Apart from bumping the GRPC message size, I think it makes sense to stop returning the full dump on `check`.

### PR DESCRIPTION
**Pull request by konnov**
Closes #1458. Since I've run into #1458 once again, I did a search through [grpc-node](https://github.com/grpc/grpc-node). This PR:

- [x] bumps the version of `grpc-js`, though this did not solve the issue directly
- [x] bumps `grpc.max_receive_message_length` and `grpc.max_send_message_length` to 1G. It's a lot, but as discussed in #1458, the Apalache integration may return a very large JSON file. I believe a proper solution would be to figure out, why this JSON result is required, and figure out compression in GRPC.
- [x] Entries added to the respective `CHANGELOG.md` for any new functionality

### CODE REVIEW

**Comment by bugarela** [comment]
Hi Igor! Last time I had to increase the message size, I had to do it in Apalache's side (see https://github.com/apalache-mc/apalache/pull/2847/files). Does this work without changing Apalache?

**Comment by konnov** [comment]
> Hi Igor! Last time I had to increase the message size, I had to do it in Apalache's side (see https://github.com/apalache-mc/apalache/pull/2847/files). Does this work without changing Apalache?

Yes, it worked for me. If it breaks on sending messages, we can also bump it in Apalache

**Review by bugarela — APPROVED** [review]
Ok then! I guess, if we end up needing to bump Apalache, we can revert this one. But if it is working for you, then it should not be necessary :smile:

**Comment by bugarela** [comment]
> > Ok then! I guess, if we end up needing to bump Apalache, we can revert this one. But if it is working for you, then it should not be necessary 😄
> 
> I think you have to merge this PR, I don't have any buttons to click

Right! Sorry. Merging now.

**Pull request merged**
